POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpxcnIiLCJpZCI6IjVlMTYzYTI2NjFjY2Q5MTQ4ZGIzMGRkNiIsImlhdCI6MTU3ODUxNDk4Mn0.EhIazrFDFO36E72sAnH3s5kDuHid9dQ-Bit754fl9U8

{
    "title": "Nunune",
    "author": "Some author",
    "url": "Some URL",
    "likes": 12
}
